### PR TITLE
Add Linking of Window-Contact Emulation [WIP]

### PR DESCRIPTION
**Pull request by Flole998**
This is entirely untested and my first approach. Most likely we still need to make more modifications.

### CODE REVIEW

**Comment by hfedcba** [comment]
Hey @Flole998,

thank you! Could you please check if the changes work? After that I'm happy to merge the pull request. It could be enough to add the windows state packet to the device's XML file. If you send me the (e. g. sniffed) packet, I can quickly do that.

Cheers,

Sathya

**Comment by Flole998** [comment]
Is there any kind of build system that could automatically generate an ARM .deb package from this for a raspberry pi? Would be great if I can get around setting something up that is at least somehow already existing.

**Comment by hfedcba** [comment]
Yes, there is: https://hub.docker.com/r/homegear/build

`docker run -it homegear/build:raspbian-stretch-armhf`

There you can install the current Homegear nightly using the nightly installer:

`wget -O /tmp/InstallNightly.sh https://downloads.homegear.eu/InstallNightly.sh && bash /tmp/InstallNightly.sh`

And after that compile any Homegear modules (just run the provided `makeDebug.sh`).

Cheers,

Sathya

**Comment by Flole998** [comment]
Unfortunately I still haven't really found time to test this. I was hoping for something like travis that automatically runs a build so I don't have to install a full docker and whatnot just to build it. Maybe someone else can test this or at least build this for me.....

**Comment by hfedcba** [comment]
Building is not the issue - I can do that. Testing is. I can compile the package for you for a given base library version, if you send me the base library version, the Linux distribution name and the architecture. But I'll need to setup exactly the same ;-).

**Comment by Flole998** [comment]
That would help me a lot, I am using the repo
`deb https://apt.homegear.eu/Raspbian/ buster/`
on a Raspberry Pi 3 (armv7l). 

Unfortunately homegear itself won't tell me much about the base version:
```
$ homegear -v
Homegear version 0.7.41-3071
Copyright (c) 2013-2019 Homegear GmbH

Git commit SHA of libhomegear-base: -
Git branch of libhomegear-base:     -
Git commit SHA of Homegear:         -
Git branch of Homegear:             -

PHP (License: PHP License):
This product includes PHP software, freely available from <http://www.php.net/software/>
Copyright (c) 1999-2019 The PHP Group. All rights reserved.
```

**Comment by hfedcba** [comment]
The Homegear version is taken from the base library version, so it's the same.

**Comment by hfedcba** [comment]
It's not compiling. Could you merge the module with the current dev branch?

**Comment by Flole998** [comment]
I tried, I hope that worked out as planned ;)

There's most likely a small syntax error somewhere that I didn't see yet....

**Comment by hfedcba** [comment]
First of all thank you! I'd like to merge, but there are merge conflicts... Could you please resolve them?

**Comment by Flole998** [comment]
This is work in progress (and actually completely broken and untested), don't merge this ;) There's a better solution being developed by @kjabl at the moment, at least for wall thermostats but once the basic structure is there it's easy to add the window contact aswell.

**Comment by hfedcba** [comment]
> This is work in progress (and actually completely broken and untested), don't merge this ;) There's a better solution being developed by @kjabl at the moment, at least for wall thermostats but once the basic structure is there it's easy to add the window contact aswell.

ok, looking forward to it. Thank you nevertheless!

**Pull request closed without merging**
